version: "3"

services:
  backend:
    build: backend/
    container_name: backend
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    depends_on: 
      - db

  recommendations:
    build: recommendation_engine/
    container_name: recommendation_engine
    depends_on: 
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build: frontend/
    ports:
      - "3000:3000"

volumes:
  postgres-data:
