version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build: backend/
    container_name: backend
    ports:
      - "5000:5000"

  frontend:
    container_name: frontend
    build: frontend/
    ports:
      - "8080:8080"


