version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  backend:
    build: backend/
    container_name: backend
    ports:
      - "5000:5000"

  frontend:
    container_name: frontend
    build: frontend/
    ports:
      - "8080:8080"

volumes:
  postgres-data:

